//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfAppShaitanat.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalFood_Sale
    {
        public int ID { get; set; }
        public Nullable<int> ID_AF { get; set; }
        public Nullable<int> SaleCapacity { get; set; }
    
        public virtual AnimalFood AnimalFood { get; set; }
    }
}
